language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION="<1.9"
  - DJANGO_VERSION="<1.10"
  - DJANGO_VERSION="<1.11"
  - DJANGO_VERSION="<1.12"
  - DJANGO_VERSION="<2.1"
  - DJANGO_VERSION="<2.2"
  - DJANGO_VERSION="<2.3"

matrix:
  exclude:
    - { python: "2.7", env: DJANGO_VERSION="<2.1" }
    - { python: "2.7", env: DJANGO_VERSION="<2.2" }
    - { python: "2.7", env: DJANGO_VERSION="<2.3" }

install:
  - pip install -U -r requirements.txt
  - pip install -U "Django$DJANGO_VERSION"

script:
  - python tools.py test
